import json
import re
from datetime import datetime
from graph.state import AgentState
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage


REPORT_PROMPT = """You are a clinical pharmacist writing a formal drug interaction report.

Write a concise clinical summary (2-3 paragraphs) covering:
1. Overall safety assessment
2. Key interactions/contraindications found
3. Clinical recommendations

Return ONLY valid JSON:
{
  "clinical_summary": "Your paragraph summary here",
  "key_recommendations": ["recommendation 1", "recommendation 2"],
  "follow_up_required": true/false,
  "urgency": "ROUTINE/URGENT/EMERGENCY"
}"""


def report_node(state: AgentState) -> AgentState:
    drugs = state.get("drugs", [])
    interactions = state.get("interactions", [])
    contraindications = state.get("contraindications", [])
    alternatives = state.get("alternatives", [])
    web_findings = state.get("web_findings", [])
    severity_score = state.get("severity_score", "SAFE")
    patient_info = state.get("patient_info", {})

    context = {
        "drugs": drugs,
        "patient_info": patient_info,
        "severity_score": severity_score,
        "interactions": interactions,
        "contraindications": contraindications,
        "alternatives": alternatives,
        "web_findings": web_findings
    }

    clinical_summary = ""
    recommendations = []
    follow_up = False
    urgency = "ROUTINE"

    try:
        llm = ChatOllama(model="llama3.2", temperature=0.1)
        messages = [
            SystemMessage(content=REPORT_PROMPT),
            HumanMessage(content=f"Generate report for:\n{json.dumps(context, indent=2)}")
        ]
        response = llm.invoke(messages)
        content = response.content.strip()

        json_match = re.search(r'\{.*\}', content, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group())
            clinical_summary = parsed.get("clinical_summary", "")
            recommendations = parsed.get("key_recommendations", [])
            follow_up = parsed.get("follow_up_required", False)
            urgency = parsed.get("urgency", "ROUTINE")
    except Exception:
        clinical_summary = f"Drug interaction check completed for {len(drugs)} medications with overall severity: {severity_score}."
        recommendations = ["Consult prescribing physician before making any changes"]

    report = {
        "report_id": f"DIC-{datetime.now().strftime('%Y%m%d%H%M%S')}",
        "generated_at": datetime.now().isoformat(),
        "overall_severity": severity_score,
        "urgency": urgency,
        "follow_up_required": follow_up,
        "drugs_analyzed": [d["name"] for d in drugs],
        "patient_info": patient_info,
        "clinical_summary": clinical_summary,
        "key_recommendations": recommendations,
        "interactions": interactions,
        "contraindications": contraindications,
        "alternatives": alternatives,
        "web_findings": web_findings,
        "disclaimer": (
            "This report is generated by an AI system for informational purposes only. "
            "It does not constitute medical advice. Always consult a qualified healthcare "
            "professional before making any medication changes."
        )
    }

    return {**state, "report": report}
